# SETTINGS #
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# PLAYER PROPERTIES #
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 250
PLAYER_ACCELERATION = 700
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3
PLAYER_HIT_COOLDOWN = 2

# ASTROID PROPERTIES #
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# OTHER ELEMENTS
SHOT_RADIUS = 5
LINE_WIDTH = 2
FRICTION_DRAG = 0.97

# POWERUP PROPERTIES
# General
TIME_LEFT_BEFORE_ITEM_DESPAWN = 8
ITEM_WIDTH = 40
ITEM_HEIGHT = 25
BOMB_EXPLOSION_RADIUS_EXPANSION = 3.5
# Spawning
BOMB_SPAWN_CHANCE = 10
SHIELD_SPAWN_CHANCE = 10
HEALTH_SPAWN_CHANCE = 10
# Bomb
BOMB_DETONATE_COUNTDOWN_TIME = 2
MAX_BOMB_EXPLOSION_TIME = 1.2
# Shield
SHIELD_RADIUS = 40
SHIELD_ITEM_PICKUP_RADIUS = 6
SHIELD_ACTIVE_TIME = 20
SHIELD_MAX_HIT = 3
SHIELD_HIT_COOLDOWN = 2
# Health
HEALTH_PICKUP_RADIUS = 15